// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using TrekkShare.Data;

namespace TrekkShare.Data.Migrations
{
    [DbContext(typeof(TrekkShareContext))]
    partial class TrekkShareContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrekkShare.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TownId");

                    b.HasKey("AddressId");

                    b.HasIndex("TownId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("TrekkShare.Models.Cave", b =>
                {
                    b.Property<int>("CaveId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EndingTime");

                    b.Property<Point>("GeoLocation");

                    b.Property<int>("GeoLocationId");

                    b.Property<int>("MountainId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<int>("StartingTime");

                    b.Property<decimal>("TicketPrice");

                    b.Property<int>("TimeIntervalWithGuide");

                    b.HasKey("CaveId");

                    b.HasIndex("GeoLocationId");

                    b.HasIndex("MountainId");

                    b.ToTable("Caves");
                });

            modelBuilder.Entity("TrekkShare.Models.Cottage", b =>
                {
                    b.Property<int>("CottageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity");

                    b.Property<Point>("GeoLocation");

                    b.Property<int>("GeoLocationId");

                    b.Property<int>("MountainId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("CottageId");

                    b.HasIndex("GeoLocationId");

                    b.HasIndex("MountainId");

                    b.ToTable("Cottages");
                });

            modelBuilder.Entity("TrekkShare.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TrekkShare.Models.GeoLocation", b =>
                {
                    b.Property<int>("GeoLocationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Point>("Location");

                    b.HasKey("GeoLocationId");

                    b.ToTable("GeoLocations");
                });

            modelBuilder.Entity("TrekkShare.Models.Lake", b =>
                {
                    b.Property<int>("LakeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Depth");

                    b.Property<Point>("GeoLocation");

                    b.Property<int>("GeoLocationId");

                    b.Property<int>("MountainId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Surface");

                    b.HasKey("LakeId");

                    b.HasIndex("GeoLocationId");

                    b.HasIndex("MountainId");

                    b.ToTable("Lakes");
                });

            modelBuilder.Entity("TrekkShare.Models.Mountain", b =>
                {
                    b.Property<int>("MountainId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Altitude");

                    b.Property<int>("CountryId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("MountainId");

                    b.HasIndex("CountryId");

                    b.ToTable("Mountains");
                });

            modelBuilder.Entity("TrekkShare.Models.MountainRiver", b =>
                {
                    b.Property<int>("MountainId");

                    b.Property<int>("RiverId");

                    b.HasKey("MountainId", "RiverId");

                    b.HasIndex("RiverId");

                    b.ToTable("MountainRiver");
                });

            modelBuilder.Entity("TrekkShare.Models.Municipality", b =>
                {
                    b.Property<int>("MunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("ProvinceId");

                    b.HasKey("MunicipalityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("TrekkShare.Models.Peak", b =>
                {
                    b.Property<int>("PeakId");

                    b.Property<int>("DifficultyLevel");

                    b.Property<Point>("GeoLocation");

                    b.Property<int>("GeoLocationId");

                    b.Property<int>("MountainId");

                    b.Property<int>("PeakElevation");

                    b.Property<string>("PeakName")
                        .IsRequired();

                    b.HasKey("PeakId");

                    b.HasIndex("GeoLocationId");

                    b.ToTable("Peaks");
                });

            modelBuilder.Entity("TrekkShare.Models.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("TrekkShare.Models.River", b =>
                {
                    b.Property<int>("RiverId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Depth");

                    b.Property<double>("Discharge");

                    b.Property<int>("Elevation");

                    b.Property<int>("FlowStrength");

                    b.Property<int>("Length");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Width");

                    b.HasKey("RiverId");

                    b.ToTable("Rivers");
                });

            modelBuilder.Entity("TrekkShare.Models.RiverCountry", b =>
                {
                    b.Property<int>("CountryId");

                    b.Property<int>("RiverId");

                    b.HasKey("CountryId", "RiverId");

                    b.HasIndex("RiverId");

                    b.ToTable("RiverCountries");
                });

            modelBuilder.Entity("TrekkShare.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Denivelation");

                    b.Property<int>("DifficultyLevel");

                    b.Property<double>("EndLatitude");

                    b.Property<double>("EndLongitude");

                    b.Property<double>("Length");

                    b.Property<int>("MountainId");

                    b.Property<int>("RecommendedEquipmentLevel");

                    b.Property<double>("StartLatitude");

                    b.Property<double>("StartLongitude");

                    b.Property<int>("TerrainType");

                    b.HasKey("RouteId");

                    b.HasIndex("MountainId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("TrekkShare.Models.Tourist", b =>
                {
                    b.Property<int>("TouristId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Experience");

                    b.Property<Guid>("UserId");

                    b.HasKey("TouristId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Tourists");
                });

            modelBuilder.Entity("TrekkShare.Models.TouristTrip", b =>
                {
                    b.Property<int>("TouristId");

                    b.Property<int>("TripId");

                    b.Property<DateTime>("DateTime");

                    b.HasKey("TouristId", "TripId");

                    b.HasIndex("TripId");

                    b.ToTable("TouristTrips");
                });

            modelBuilder.Entity("TrekkShare.Models.Town", b =>
                {
                    b.Property<int>("TownId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MunicipalityId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("TownId");

                    b.HasIndex("MunicipalityId");

                    b.ToTable("Towns");
                });

            modelBuilder.Entity("TrekkShare.Models.Transport", b =>
                {
                    b.Property<int>("TransportId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArrivalTime");

                    b.Property<int>("AvailableSeats");

                    b.Property<string>("DepartureAddress")
                        .IsRequired();

                    b.Property<DateTime>("DepartureTime");

                    b.Property<decimal>("ExpectedCostPerPerson");

                    b.Property<int>("TransportType");

                    b.Property<int>("TripId");

                    b.HasKey("TransportId");

                    b.HasIndex("TripId");

                    b.ToTable("Transports");
                });

            modelBuilder.Entity("TrekkShare.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CottageId");

                    b.Property<Point>("EndPoint");

                    b.Property<int>("EndPointId");

                    b.Property<TimeSpan>("Length");

                    b.Property<int>("MaxTouristsCount");

                    b.Property<int>("NightsCount");

                    b.Property<int>("RouteId");

                    b.Property<Point>("StartPoint");

                    b.Property<int>("StartPointId");

                    b.HasKey("TripId");

                    b.HasIndex("CottageId");

                    b.HasIndex("RouteId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TrekkShare.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddressId");

                    b.Property<int>("Age");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)")
                        .HasMaxLength(60)
                        .IsUnicode(true);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Password");

                    b.Property<string>("Phone")
                        .HasMaxLength(30);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasMaxLength(30)
                        .IsUnicode(true);

                    b.HasKey("UserId");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrekkShare.Models.Waterfall", b =>
                {
                    b.Property<int>("WaterfallId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(400);

                    b.Property<string>("DomesticName")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<int?>("FlowRate");

                    b.Property<int?>("Height");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<int>("RiverId");

                    b.Property<int?>("Width");

                    b.HasKey("WaterfallId");

                    b.HasIndex("RiverId");

                    b.ToTable("Waterfalls");
                });

            modelBuilder.Entity("TrekkShare.Models.Address", b =>
                {
                    b.HasOne("TrekkShare.Models.Town", "Town")
                        .WithMany("Addresses")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrekkShare.Models.Cave", b =>
                {
                    b.HasOne("TrekkShare.Models.GeoLocation")
                        .WithMany("Caves")
                        .HasForeignKey("GeoLocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrekkShare.Models.Mountain", "Mountain")
                        .WithMany("Caves")
                        .HasForeignKey("MountainId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrekkShare.Models.Cottage", b =>
                {
                    b.HasOne("TrekkShare.Models.GeoLocation")
                        .WithMany("Cottages")
                        .HasForeignKey("GeoLocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrekkShare.Models.Mountain", "Mountain")
                        .WithMany("Cottages")
                        .HasForeignKey("MountainId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrekkShare.Models.Lake", b =>
                {
                    b.HasOne("TrekkShare.Models.GeoLocation")
                        .WithMany("Lakes")
                        .HasForeignKey("GeoLocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrekkShare.Models.Mountain", "Mountain")
                        .WithMany("Lakes")
                        .HasForeignKey("MountainId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrekkShare.Models.Mountain", b =>
                {
                    b.HasOne("TrekkShare.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrekkShare.Models.MountainRiver", b =>
                {
                    b.HasOne("TrekkShare.Models.Mountain", "Mountain")
                        .WithMany("MountainRivers")
                        .HasForeignKey("MountainId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrekkShare.Models.River", "River")
                        .WithMany("MountainRivers")
                        .HasForeignKey("RiverId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TrekkShare.Models.Municipality", b =>
                {
                    b.HasOne("TrekkShare.Models.Country", "Country")
                        .WithMany("Municipalities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrekkShare.Models.Province")
                        .WithMany("Municipalities")
                        .HasForeignKey("ProvinceId");
                });

            modelBuilder.Entity("TrekkShare.Models.Peak", b =>
                {
                    b.HasOne("TrekkShare.Models.GeoLocation")
                        .WithMany("Peaks")
                        .HasForeignKey("GeoLocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TrekkShare.Models.Mountain", "Mountain")
                        .WithMany("Peaks")
                        .HasForeignKey("PeakId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TrekkShare.Models.RiverCountry", b =>
                {
                    b.HasOne("TrekkShare.Models.Country", "Country")
                        .WithMany("RiverCountries")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrekkShare.Models.River", "River")
                        .WithMany("RiverCountries")
                        .HasForeignKey("RiverId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TrekkShare.Models.Route", b =>
                {
                    b.HasOne("TrekkShare.Models.Mountain", "Mountain")
                        .WithMany("Routes")
                        .HasForeignKey("MountainId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrekkShare.Models.Tourist", b =>
                {
                    b.HasOne("TrekkShare.Models.User", "User")
                        .WithOne("Tourist")
                        .HasForeignKey("TrekkShare.Models.Tourist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrekkShare.Models.TouristTrip", b =>
                {
                    b.HasOne("TrekkShare.Models.Tourist", "Tourist")
                        .WithMany("TouristTrips")
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TrekkShare.Models.Trip", "Trip")
                        .WithMany("TouristTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TrekkShare.Models.Town", b =>
                {
                    b.HasOne("TrekkShare.Models.Municipality", "Municipality")
                        .WithMany("Towns")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrekkShare.Models.Transport", b =>
                {
                    b.HasOne("TrekkShare.Models.Trip", "Trip")
                        .WithMany("Transports")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrekkShare.Models.Trip", b =>
                {
                    b.HasOne("TrekkShare.Models.Cottage", "Cottage")
                        .WithMany()
                        .HasForeignKey("CottageId");

                    b.HasOne("TrekkShare.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrekkShare.Models.User", b =>
                {
                    b.HasOne("TrekkShare.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrekkShare.Models.Waterfall", b =>
                {
                    b.HasOne("TrekkShare.Models.River", "River")
                        .WithMany("Waterfalls")
                        .HasForeignKey("RiverId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
